name: Build Android

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Zipaling
        run: sudo apt-get update && sudo apt-get install zipalign
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Capacitor
        run: npm install -g @capacitor/cli

      - name: Install Ionic
        run: npm install -g @ionic/cli native-run cordova-res

      - name: Install app dependencies
        run: npm install
        
      - name: Build Web App
        run: npm run build
        
      - name: Add Android platform
        run: ionic capacitor add android

      - name: Build Android Dev APK
        run: ionic capacitor build android --no-open

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod --no-open

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew assembleDebug
      
      - name: Generate the Android App Release
        working-directory: ./android/
        run: ./gradlew assembleRelease

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: KeyTool
        working-directory: "${{ env.JAVA_HOME }}"
        run: keytool -genkey -v -keystore ejemplo.keystore -alias laucha -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=Lautaro Carro, OU=LauchaTech, O=LauchaTech, L=CABA, S=BuenosAires, C=AR" && ls
      
      - name: Upload firma
        uses: actions/upload-artifact@v1
        with:
          name: keystore
          path: '${{ env.JAVA_HOME }}/ejemplo.keystore'
      
      - name: Jarsigner
        working-directory: "${{ env.JAVA_HOME }}"
        run: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ejemplo.keystore -storepass "password" -keypass "password" '/home/runner/work/Reserva2ClientApp/Reserva2ClientApp/android/app/build/outputs/apk/release/app-release-unsigned.apk' laucha && ls
      
      - name: Upload release signed apk
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: '/home/runner/work/Reserva2ClientApp/Reserva2ClientApp/android/app/build/outputs/apk/release/app-release-unsigned.apk'
      
      - name: Zipalign 
        run: zipalign -v 4 '/home/runner/work/Reserva2ClientApp/Reserva2ClientApp/android/app/build/outputs/apk/release/app-release-unsigned.apk' ejemplo.apk && ls

      - name: Upload release signed optimize apk
        uses: actions/upload-artifact@v1
        with:
          name: app-release-opt
          path: ejemplo.apk
        
